### ISSUE TITLE
No such interface exists 

### ISSUE THREAD

**Issue by CaptainStabs** [seemoo-lab/owl#16]
I'm using the Alfa AWUS036NHA (Atheros AR9271)
Monitor mode works with airmon-ng, if i try to set owl to use the wlan interface created by airmon-ng I get the

iwconfig:
`wlx00c0ca981c63  IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off`
I've tried it with it in monitor mode already, but I get the same problem

`sudo owl -N wlx00c0ca981c63`
Gives the same problem of `No such interface exists`

`sudo owl -i wlx00c0ca981c63`
outputs:
`ERROR: Error while receiving via netlink: Operation not supported
ERROR: Could not put device in monitor mode: wlx00c0ca981c63
ERROR: could not initialize core`

**Comment by schmittner** [comment]
You are missing `-i` in the first call. Please read the docs before opening an issue.
