### ISSUE TITLE
Could  we build a socket

### ISSUE THREAD

**Issue by spadejack014** [seemoo-lab/owl#17]
I want to build a socket via it. It is connect via ping. but I cannot build an TCP socket via it.

**Comment by notpushkin** [comment]
Have you tried https://github.com/seemoo-lab/proxawdl?

**Comment by schmittner** [comment]
Yes, this is also possible with OWL. For example, [OpenDrop](https://github.com/seemoo-lab/opendrop) uses OWL to setup HTTPS connections.
