### ISSUE TITLE
ESP32 Support?

### ISSUE THREAD

**Issue by 0x77dev** [seemoo-lab/owl#23]
ESP32 Microcontroller support.

**Comment by schmittner** [comment]
Good idea. Unfortunately, I do not have time/resources to work on this.

**Comment by 0x77dev** [comment]
I will try... If what can I ask you for some questions?

**Comment by schmittner** [comment]
I can try to support, even though my experience with ESP32 is extremely limited.
At a minimum, you'll have to implement `io.h` and `netutils.h`, and also check whether `libev` is supported on ESP32.

**Comment by 0x77dev** [comment]
[libuv-like](https://github.com/alxvasilev/esp32-event)

**Comment by 0x77dev** [comment]
Ok, @schmittner thank you.

**Comment by JanBdf** [comment]
@0x77dev Have you since found the time to try this?

**Comment by 0x77dev** [comment]
I haven't and don't have time for it right now. 
But I would love to experiment with it someday!

**Comment by conradev** [comment]
It looks like `netutils.h` could be compatible with [esp_wifi](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/network/esp_wifi.html)

It would be pretty cool to be able to AirDrop to an SD card: https://github.com/FYSETC/SD-WIFI-PRO
