### ISSUE TITLE
netlink operation not supported on a macbook.

### ISSUE THREAD

**Issue by NikosEfthias** [seemoo-lab/owl#24]
I am running ubuntu on my macbook which tells me operations is not supported which is weird because on osx somehow the same device could be put in monitor mode. 
I believe this is an owl issue rather than a device support issue

**Comment by schmittner** [comment]
The Broadcom chips that Apple uses have really bad driver support under Linux, while things are much better under macOS. So, what you are experiencing is very likely **not** an OWL issue.

**Comment by tarkh** [comment]
Have similar problem. Installed Arch on Macbook 2014 and can't run OWL with same error. Network adapter is BCM4360 802.11ac [14e4:43a0] (rev 03) which works fine in both 2,4 and 5 GHz modes, BT also works ok.

I've discovered on manpage that you CAN enable monitor mode like this:
`echo 1 > /proc/brcm_monitor0`
(https://wiki.archlinux.org/title/broadcom_wireless#Setting_broadcom-wl_in_monitor_mode)

After this command mew interface `prism0` appears in system (with SAME `MAC` address as BCM4360 interface, usually called `wlp2s0`), which gives you ability to monitor network. So the question is - how can I tell OWL to use this particular device for monitoring function? Thank you!
