### ISSUE TITLE
owl or opendrop  

### ISSUE THREAD

**Issue by ariagecheney** [seemoo-lab/owl#26]
The hardware is macbookpro(10.15.1) and ipad 2018 (ipad OS 13.3.1). At the same time, kali Linux was run in the virtual machine （parallel desktop 15).
1 in the virtual machine kali, follow the steps https://github.com/seemoo-lab/owl ready, but I don't know "what is the < WLAN_IFACE >"! maybe "ifconfig "? i'm confused!
2. I don't quite understand the before-and-after dependency of opendrop and owl. Install owl first and then opendrop? "After exec "owl", then exec "opendrop"?  " .
3. In termux app, I installed debian for aarch64 with atilo script, which is for android phone to interact with MAC and ipad directly through airdrop, but I failed.
4 I sincerely hope to have a  good tutorial. My English is not very good.

**Comment by schmittner** [comment]
OWL is unsupported in virtualized environments, so your setup will not work. I added a note in the README.
