### ISSUE TITLE
Error inject packet

### ISSUE THREAD

**Issue by paverneuil** [seemoo-lab/owl#27]
Good morning, sir,
I managed to get the nexmon / OWL / Opendrop set to work under raspberry pi 4.

But I encounter an error that I don't understand where it came from:

`16:53:32 ERROR: unable to inject packet (send: Resource temporarily unavailable)`

Could you please tell me where this error could have come from?

Have a nice day.

**Comment by schmittner** [comment]
Unfortunately, Nexmon does not (yet) support frame injection on the Raspberry Pi 3B+ and 4.

**Comment by redor303** [comment]
Well now it is supported I think
