### ISSUE TITLE
Can we configure an IPv4 address for awdl0 port?

### ISSUE THREAD

**Issue by spadejack014** [seemoo-lab/owl#31]

**Comment by schmittner** [comment]
In principle you could, but you won't be able to resolve MAC addresses and, thus, you won't be able to route messages to a different device.
*Explanation:* OWL and AWDL both use a link-local IPv6 address derived from the Wi-Fi MAC address to automatically update the neighbor table of the system, without the need of running an explicit neighbor discovery (ND) protocol.
