### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by T2brozz** [seemoo-lab/owl#34]
Hey, I get an Error if I want to compile it with makepkg -si .
System : Linux t2brozz 5.6.16-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:26:28 UTC 2020 x86_64 GNU/Linux

Error
_______________________________

==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating owlink-git git repo...
Fetching origin
  -> Updating googletest git repo...
Fetching origin
  -> Updating radiotap-library git repo...
Fetching origin
==> Validating source files with sha512sums...
    owlink-git ... Skipped
    googletest ... Skipped
    radiotap-library ... Skipped
==> Extracting sources...
  -> Creating working copy of owlink-git git repo...
Reset branch 'makepkg'
  -> Creating working copy of googletest git repo...
Reset branch 'makepkg'
  -> Creating working copy of radiotap-library git repo...
Reset branch 'makepkg'
==> Starting prepare()...
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yannes/owlink-git/src/owlink-git/build
[ 10%] Built target radiotap
[ 10%] Built target gtest
[ 21%] Built target gtest_main
[ 21%] Built target gmock
Scanning dependencies of target gmock_main
[ 67%] Built target awdl
[ 70%] Building CXX object googletest/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[ 72%] Linking C executable owl
[ 86%] Built target tests
/usr/bin/ld: ../src/libawdl.a(rx.c.o):(.bss+0x0): multiple definition of `__packed'; ../src/libawdl.a(tx.c.o):(.bss+0x0): first defined here
/usr/bin/ld: ../libradiotap.a(radiotap.c.o):(.bss+0x0): multiple definition of `__packed'; ../src/libawdl.a(tx.c.o):(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [daemon/CMakeFiles/owl.dir/build.make:153: daemon/owl] Error 1
make[1]: *** [CMakeFiles/Makefile2:276: daemon/CMakeFiles/owl.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 89%] Linking CXX static library ../../lib/libgmock_main.a
[ 89%] Built target gmock_main
make: *** [Makefile:150: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

_______________________________________

I hope someone can help

**Comment by 888-222** [comment]
I have the same issue.

**Comment by schmittner** [comment]
Fixed. See #32 for details.
