### ISSUE TITLE
does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by BimLee** [seemoo-lab/owl#35]
Last login: Tue Sep  1 14:37:36 on ttys000
(base) hongleima@hongleimadeMacBook-Pro ~ % cd Downloads/owl 
(base) hongleima@hongleimadeMacBook-Pro owl % git submodule update --init
(base) hongleima@hongleimadeMacBook-Pro owl % mkdir build
(base) hongleima@hongleimadeMacBook-Pro owl % cd build
(base) hongleima@hongleimadeMacBook-Pro build % cmake ..
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found libpcap: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libpcap.tbd  
-- Found libev: /usr/local/lib/libev.dylib  
CMake Error at CMakeLists.txt:17 (add_subdirectory):
  The source directory

    /Users/hongleima/Downloads/owl/googletest

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/Users/hongleima/Downloads/owl/build/CMakeFiles/CMakeOutput.log".
(base) hongleima@hongleimadeMacBook-Pro build %

**Comment by neffs** [comment]
Follow the readme carefully:

git submodule update --init

**Comment by BimLee** [comment]
> Follow the readme carefully:
> 
> git submodule update --init

Thank you for your reply, but I have executed  code in the second line

**Comment by neffs** [comment]
If there is no CMakeLists.txt, something went wrong with the submodules. 

```
➜  build git:(master) cmake ..
-- Found libev: /usr/local/lib/libev.dylib  
CMake Error at CMakeLists.txt:17 (add_subdirectory):
  The source directory

    /Users/dk/GitHub/owl/googletest

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/Users/dk/GitHub/owl/build/CMakeFiles/CMakeOutput.log".
➜  build git:(master) git submodule update --init

Submodule 'googletest' (https://github.com/google/googletest.git) registered for path '../googletest'
Submodule 'radiotap' (https://github.com/radiotap/radiotap-library.git) registered for path '../radiotap'
Cloning into '/Users/dk/GitHub/owl/googletest'...
Cloning into '/Users/dk/GitHub/owl/radiotap'...
Submodule path '../googletest': checked out '703bd9caab50b139428cea1aaff9974ebee5742e'
Submodule path '../radiotap': checked out '94984dd829a605a2d7af55241145c159607f3b30'
➜  build git:(master) cmake ..                   
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.17") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dk/GitHub/owl/build
➜  build git:(master) ls ../googletest 
BUILD.bazel     CONTRIBUTING.md README.md       appveyor.yml    googlemock      library.json
CMakeLists.txt  LICENSE         WORKSPACE       ci              googletest      platformio.ini

```

**Comment by schmittner** [comment]
Closing this since issue seems to be solved.
