### ISSUE TITLE
Error while receiving via netlink: Operation not supported. Card supports monitor mode

### ISSUE THREAD

**Issue by worst-python-coder** [seemoo-lab/owl#46]
this problem keeps happening and I have no idea why, Details below.

`wlx00c0caad6c6e  IEEE 802.11  Mode:Monitor  Tx-Power=30 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Power Management:off`
          
Command I used:     owl -i wlx00c0caad6c6e

output: 

`14:35:27 ERROR: Error while receiving via netlink: Operation not supported
14:35:27 ERROR: Could not put device in monitor mode: wlx00c0caad6c6e
14:35:27 ERROR: could not initialize core`

running Parrot OS. Any help is appreciated.

**Comment by worst-python-coder** [comment]
The card I'm using is a Alfa AWUS036NEH

**Comment by schmittner** [comment]
It means that your Wi-Fi card does not support active monitor mode. Please consult the README.
