### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND

### ISSUE THREAD

**Issue by masrur-mmrs** [seemoo-lab/owl#47]
masrur@masrur-ubuntu:~/Downloads/owl/build$ cmake ..
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
nlroute_LIBRARY
    linked by target "owl" in directory /home/masrur/Downloads/owl/daemon

-- Configuring incomplete, errors occurred!
See also "/home/masrur/Downloads/owl/build/CMakeFiles/CMakeOutput.log".
See also "/home/masrur/Downloads/owl/build/CMakeFiles/CMakeError.log".

**Comment by schmittner** [comment]
Looks like you did not install all required netlink dependencies. Please consult the README.

**Comment by masrur-mmrs** [comment]
> Looks like you did not install all required netlink dependencies. Please consult the README.

I already installed **libcap** **libev** and **libnl** and they are up to date.

**Comment by masrur-mmrs** [comment]
Okay got the problem I had to then install
**libnl-cli-3-dev**
**libnl-genl-3-dev**
**libnl-idiag-3-dev**
**libnl-nf-3-dev**
**libnl-xfrm-3-dev**
**libnl-route-3-200**

**Comment by schmittner** [comment]
To be precise, you need

- libnl-3-dev
- libnl-genl-3-dev
- libnl-route-3-dev

... as stated in the README.
