### ISSUE TITLE
Reatlek 8821CU Cannot put device in monitor mode

### ISSUE THREAD

**Issue by y77chen** [seemoo-lab/owl#48]
Hi, I am trying to make OWL work on my USB Wifi Adapter which is based on chip Reatlek 8821CU. I have already installed [driver](https://github.com/brektrou/rtl8821CU) on it, with "CONFIG_WIFI_MONITOR" option on. 

However, when I am trying to activate OWL with command `sudo owl -i wlan1` where wlan1 is the corresponding interface, I get the error of 

```
ERROR: Error while receiving via netlink: Operation not supported
ERROR: Could not put device in monitor mode: wlan1
ERROR: could not initialize core 
```

even though I have turned on the monitor mode by using iw. Here is the output of `sudo iw dev` which shows that I have monitor mode turned on:

```
phy#6
        Interface wlan1
                ifindex 12
                wdev 0x600000001
                addr 20:0d:b0:4f:33:77
                type monitor
                txpower 12.00 dBm
phy#0
        Unnamed/non-netdev interface
                wdev 0x3
                addr 34:2e:b7:17:4d:00
                type P2P-device
                txpower 0.00 dBm
        Interface wlan0
                ifindex 5
                wdev 0x2
                addr 34:2e:b7:17:4d:ff
                ssid WIFI-CZ
                type managed
                channel 1 (2412 MHz), width: 20 MHz, center1: 2412 MHz
                txpower 22.00 dBm
                multicast TXQ:
                        qsz-byt qsz-pkt flows   drops   marks   overlmt hashcol tx-bytes        tx-packets
                        0       0       0       0       0       0       0       0               0
```

I am not quite sure what happened to make this not working. Any help is appreciated, thanks.

**Comment by schmittner** [comment]
Please read https://github.com/seemoo-lab/owl/issues/9#issuecomment-522974897

**Comment by y77chen** [comment]
Hi, I do not think that my problem belongs to the situation described in #9. As you can see in my description, the card I am using is actually capable of active monitoring mode.

If that is not clear enough, here is the relevant content of using `iw phy phy1 info`:
```
Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * monitor
                 * P2P-client
                 * P2P-GO
```

I appologize if I am misinterpreting anything.

**Comment by schmittner** [comment]
There is no mention of _**active**_ monitor mode in the output.

**Comment by y77chen** [comment]
Hi, sorry, my bad.
