### ISSUE TITLE
 Not working on macOS 10.14

### ISSUE THREAD

**Issue by jtsylve** [seemoo-lab/owl#5]
When trying to run on macOS 10.14 I get the following errors

```
16:51:34 TRACE: pcap: unable to open savefile (en0: No such file or directory)
16:51:34 ERROR: tun: cannot open available device
16:51:34 ERROR: Could not open device: awdl0
16:51:34 ERROR: could not initialize core
```

Looking at the code it seems to be trying to open a `/dev/tun0` device that doesn't seem to exist.  What am I doing wrong?

**Comment by schmittner** [comment]
Correct, macOS does not have native support for tun/tap devices, so you'll need to install tuntaposx. For example, with homebrew: `brew cask install tuntap`.

**Comment by osehgol** [comment]
for mac 10.15.3 (Catalina), mac security blocks brew installation of tuntap. to overcome `System Preferences`-> `Security and Privacy` -> `General` -> `Allow app downloaded from: App Store and Identified developers` and (verify, then) unblock developer

**Comment by Ocelot124286** [comment]
Can you help me? Mine opens a tun0 interface instead of awdl0. It doesn’t seem to have a awdl0 interface at all.

**Comment by osehgol** [comment]
sure. i did this a while back `sudo owl -i -D -vv en0` (on mac)  
and awdl0 became active. if this doesn't work let me know ill get back to it

**Comment by Ocelot124286** [comment]
Yeah so I tried that and it didn’t create awdl0, instead it always seems to create tun0.

**Comment by SalilJain** [comment]
> Yeah so I tried that and it didn’t create awdl0, instead it always seems to create tun0.

@Ocelot124286  you may want to try following command:
opendrop find -i tun0
